spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/mcwf_test_mem/db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9091;DB_CLOSE_DELAY=-1
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  level:
    root: INFO
    org:
      hibernate:
        sql: DEBUG